[project]
name = "VizFun"
version = "0.1.0"
description = "Add a short description here"
authors = ["Rahul Dave <rahuldave@gmail.com>"]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tasks]

[dependencies]
matplotlib = ">=3.8.4,<3.9"
pandas = ">=2.2.1,<2.3"
jupyter = ">=1.0.0,<1.1"
python = ">=3.12.2,<3.13"
numpy = ">=1.26.4,<1.27"
pytest = ">=8.1.1,<8.2"
